"""empty message

Revision ID: 187f8cffb26f
Revises: 052e0a6ff4b8
Create Date: 2024-08-25 13:31:41.183781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187f8cffb26f'
down_revision = '052e0a6ff4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshii_data', schema=None) as batch_op:
        batch_op.alter_column('updated_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshii_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
