"""empty message

Revision ID: 8c21881bb391
Revises: 13e430acf1eb
Create Date: 2024-08-24 01:04:16.385201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c21881bb391'
down_revision = '13e430acf1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshii_data', schema=None) as batch_op:
        batch_op.drop_constraint('freshii_data_date_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshii_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('freshii_data_date_key', ['date'])

    # ### end Alembic commands ###
