"""empty message

Revision ID: b085f25d575a
Revises: 8c21881bb391
Create Date: 2024-08-24 01:12:26.529583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b085f25d575a'
down_revision = '8c21881bb391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshii_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('freshii_data_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('freshii_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('freshii_data_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###
